name: Deploy AWS Lambda Function

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
       
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
       
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          cd lambda-example
          npm install
          
      - name: Package Lambda function
        run: |
          cd lambda-example
          zip -r ../lambda-function.zip ./*
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::123456789012:role/GitHubActionsDeployRole
          aws-region: us-west-2
    
      - name: Deploy Lambda
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: test-lambda
          zip-file-path: ./lambda-function.zip
          memory-size: 256
          publish: true
